var codropsEvents = {
	
	'12-31-2016' : '<a href="http://ajplus.net/">  New Year\'s Eve </a>',
	'12-25-2016' : '<a href="http://ajplus.net/"> Christmas  </a>',
	'12-08-2016' : '<a href="http://ajplus.net/"> TIME Person of the Year </a>',
        '11-28-2016' : '<a href="http://ajplus.net/"> UN Climate Conference, France </a>',
	'11-25-2016' : '<a href="http://ajplus.net/"> Black Friday U.S. </a>',
 	'11-24-2016' : '<a href="http://ajplus.net/"> Thanksgiving U.S. </a>',
 	'11-17-2016' : '<a href="http://ajplus.net/">APEC Philippines </a>',
 	'11-11-2016' : '<a href="http://ajplus.net/">Veterans Day </a>',
 	'11-08-2016' : '<a href="http://ajplus.net/">U.S. Pres Election </a>',
 	'10-31-2016' : '<a href="http://ajplus.net/"> Halloween</a>',
 	'10-30-2016' : '<a href="http://ajplus.net/">Tunisia Municipal & <br> Regional Elections  </a>',
 	'10-10-2016' : '<a href="http://ajplus.net/">Columbus Day U.S.  </a>',
 	'10-07-2016' : '<a href="http://ajplus.net/">Nobel Winner Announced </a>',
 	'10-05-2016' : '<a href="http://ajplus.net/"> 2nd Our Ocean Conf. Chile</a> <a href="http://ajplus.net/">Vice Presidential Debate, VA</a>',
 	'09-26-2016' : '<a href="http://ajplus.net/">70th UNGAS Debate, New York </a><a href="http://ajplus.net/">First Presidential Debate, OH </a>',
 	'09-13-2016' : '<a href="http://ajplus.net/">71st UNGAS New York </a>',
 	'09-05-2016' : '<a href="http://ajplus.net/">Labor Day</a>',
 	'09-18-2016' : '<a href="http://ajplus.net/">Russian Parliamentary Elections</a>',
	'09-01-2016' : '<a href="http://ajplus.net/"> Labor Day Weekend</a>',
 	'08-05-2016' : '<a href="http://ajplus.net/">Olympics Brazil </a>',
 	'07-29-2016' : '<a href="http://ajplus.net/">129th IOC Session, Rio</a>',
 	'07-28-2016' : '<a href="http://ajplus.net/"> DNC Convention, Philadephia, PA </a>',	
 	'07-27-2016' : '<a href="http://ajplus.net/"> DNC Convention, Philadephia, PA </a>',	
 	'07-26-2016' : '<a href="http://ajplus.net/"> DNC Convention, Philadephia, PA </a>',	
 	'07-25-2016' : '<a href="http://ajplus.net/"> DNC Convention, Philadephia, PA </a>',	
 	'07-21-2016' : '<a href="http://ajplus.net/"> GOP Convention, Cleveland, OH </a>',
 	'07-20-2016' : '<a href="http://ajplus.net/"> GOP Convention, Cleveland, OH </a>',	
 	'07-19-2016' : '<a href="http://ajplus.net/"> GOP Convention, Cleveland, OH </a>',	
 	'07-18-2016' : '<a href="http://ajplus.net/"> GOP Convention, Cleveland, OH </a>',	
        '07-04-2016' : '<a href="http://ajplus.net/"> Independence Day U.S. </a>',
	'07-04-2016' : '<a href="http://ajplus.net/"> Jupiter Mission</a>',
	'06-20-2016' : '<a href="http://ajplus.net/"> Summer Solstice</a>',
	'06-14-2016' : '<a href="http://ajplus.net/"> Primaries: <br> District of Columbia <br> TBD: <br> North Dakota <br> Maine <br> Wyoming  </a>',	
	'06-05-2016' : '<a href="http://ajplus.net/"> Primaries: <br> Puerto Rico (Dem)  </a>',	
	'06-07-2016' : '<a href="http://ajplus.net/"> Primaries: <br> California <br> Montana <br> New Jersey <br> New Mexico <br> South Dakota </a>',	
	'05-30-2016' : '<a href="http://ajplus.net/"> Memorial Day U.S. </a>',	
	'05-17-2016' : '<a href="http://ajplus.net/"> Primaries: <br> Kentucky (Dem) <br> Oregon </a>',	
	'05-10-2016' : '<a href="http://ajplus.net/"> Primaries: <br> Nebraska (GOP) <br> West Virginia</a>',		
	'05-08-2016' : '<a href="http://ajplus.net/"> Mother\'s Day </a>',
	'05-03-2016' : '<a href="http://ajplus.net/"> Primaries: <br> Indiana</a>',
	'05-01-2016' : '<a href="http://ajplus.net/">Daytime Emmy Awards</a>',
	'04-26-2016' : '<a href="http://ajplus.net/">Primaries: <br> Connecticut <br> Delaware <br> Maryland <br> Pennsylvania <br> Rhode Island</a>',
	'04-24-2016' : '<a href="http://ajplus.net/">Obama in Germany </a>',
	'04-21-2016' : '<a href="http://ajplus.net/">Queen Elizabeth 90th  </a>',
	'04-19-2016' : '<a href="http://ajplus.net/"> Primaries: <br> New York </a>',
	'04-22-2016' : '<a href="http://ajplus.net/">Earth Day</a>',
	'04-18-2016' : '<a href="http://ajplus.net/">Boston Marathon</a>',
	'04-17-2016' : '<a href="http://ajplus.net/">World Bank Spring Meetings</a>',
	'04-16-2016' : '<a href="http://ajplus.net/">World Bank Spring Meetings</a>',
	'04-15-2016' : '<a href="http://ajplus.net/">World Bank Spring Meetings</a>',
	'04-15-2016' : '<a href="http://ajplus.net/">Boston Bombing, 3rd Anniverssary </a>',
	'04-12-2016' : '<a href="https://www.fbf8.com/">F8 Facebook <br> Developer Conference  </a>',
	'04-04-2016' : '<a href="http://ajplus.net/">Saskatchewan <br> Election </a>',
	'02-29-2016' : '<a href="http://ajplus.net/">Leap Day</a>',
	'04-02-2016' : '<a href="http://ajplus.net/">March Madness, Final Hour</a>',				
	'03-27-2016' : '<a href="http://ajplus.net/">Easter Sunday</a>',
	'03-26-2016' : '<a href="http://ajplus.net/">Caucuses: <br> Alaska (Dem) <br> Hawaii (Dem) <br> Washington (Dem) </a>',
	'03-25-2016' : '<a href="https://www.youtube.com/ajplus/">AJ+ Doc: <br> Ceasefire</a>',
	'03-24-2016' : '<a href="http://ajplus.net/">Obama in Cuba, <br> First Sitting <br> U.S. President <br> in 90 Years </a>',
	'03-23-2016' : '<a href="http://ajplus.net/">Obama in Cuba, <br> First Sitting <br> U.S. President <br> in 90 Years</a>',
	'03-22-2016' : '<a href="http://ajplus.net/">Obama in Cuba </a> <a href="http://ajplus.net/">Primaries: <br> Utah <br> Arizona   </a>',
	'03-21-2016' : '<a href="http://ajplus.net/">GOP Debate, Salt Lake </a><a href="https://www.whitehouse.gov/issues/foreign-policy/cuba/">Obama - Cuba </a> <a href="http://www.supremecourt.gov/qp/15-00138qp.pdf/"> SCOTUS:  NABISCO V. EU </a>',
	'03-20-2016' : '<a href="http://ajplus.net/">American Israeli <br> Public Affairs <br> Committee Conference </a>',
	'03-18-2016' : '<a href="https://www.youtube.com/ajplus/">AJ+ Doc <br> Emotional Robot</a>',
	'03-17-2016' : '<a href="http://ajplus.net/">St Patricks Day </a>',
	'03-15-2016' : '<a href="http://ajplus.net/"> Primaries: <br> Florida <br> Illinois <br> Missouri <br> North Carolina <br> Ohio </a>',
	'03-13-2016' : '<a href="http://ajplus.net/">Spring Forward - Daylight Savings </a> <a href="http://ajplus.net/">Caucuses: <br> Puerto Rico (GOP) </a>',
	'03-12-2016' : '<a href="http://www.worlddroneprix.com/event.php/">Dubai Drone Prix </a>',
	'03-11-2016' : '<a href="http://ajplus.net/">Obama at SXSW, TX </a><a href="http://www.worlddroneprix.com/">Dubai Drone Prix </a><a href="http://www.worlddroneprix.com/">Nancy Reagan Funeral </a>',
 	'03-10-2016' : '<a href="http://ajplus.net/">Trudeau at White House</a>',
 	'03-10-2016' : '<a href="http://ajplus.net/">GOP Debate on CNN </a><a href="http://ajplus.net/">Trudeau at <br> the White House </a>',
	'03-09-2016' : '<a href="http://ajplus.net/">Democrats - Univision <br> WashPo Debate </a><a href="https://deepmind.com/alpha-go.html/">Man vs Computer <br> GO Match, South Korea</a>',
	'03-06-2016' : '<a href="http://ajplus.net/"> Democratic Debate, <br> Flint, Michigan </a>',
	'03-08-2016' : '<a href="http://ajplus.net/"> Caucuses: <br> Hawaii (GOP) <br> Idaho (GOP) <br> Mississippi <br> Michigan </a>',
	'03-07-2016' : '<a href="http://ajplus.net/"> U.S., South Korea <br> Military Drills </a>',
	'03-06-2016' : '<a href="http://ajplus.net/">Caucuses <br> Kansas <br> Kentucky (GOP <br>  Louisiana <br>  Nebraska (Dem) </a>',
	'03-05-2016' : '<a href="http://ajplus.net/">GOP Caucuses <br> Puerto Rico </a>',
	'03-04-2016' : '<a href="https://www.youtube.com/ajplus/"> AJ+ Doc: Changing the Game</a>',
	'03-03-2016' : '<a href="http://www.foxnews.com/live-coverage/fox-news-gop-debate/">GOP Fox News Debate <br> Detroit</a>',
	'03-02-2016' : '<a href="http://ajplus.net/">Forbes World <br> Billionaires List <br> Announced</a>',
	'03-01-2016' : '<a href="http://ajplus.net/">Super Tuesday - U.S.   </a>',
	'02-29-2016' : '<a href="http://ajplus.net/">Leap Day</a>',
	'02-28-2016' : '<a href="http://ajplus.net/">The Oscars</a>',
	'02-27-2016' : '<a href="http://ajplus.net/">South Carolina Dem Primary</a>',
	'02-26-2016' : '<a href="http://ajplus.net/">GOP Presidential Debate, Houston, TX</a>',
	'02-23-2016' : '<a href="http://ajplus.net/">Nevada GOP Caucuses</a>',
	'02-20-2016' : '<a href="http://ajplus.net/">South Carolina GOP Primary</a>',
	'02-20-2016' : '<a href="http://ajplus.net/">Nevada Democratic Caucuses </a>',
	'02-14-2016' : '<a href="http://ajplus.net/">Valentine\'s Day</a>',
	'02-13-2016' : '<a href="http://ajplus.net/">GOP Debate, CBS </a>',
	'02-11-2016' : '<a href="http://ajplus.net/">Dem Debate PBS </a>',
	'02-09-2016' : '<a href="http://ajplus.net/">New Hampshire Presidental Primary</a>',
	'02-07-2016' : '<a href="http://ajplus.net/">SuperBowl 50 </a>',
	'02-06-2016' : '<a href="http://ajplus.net/">GOP Debate on ABC, NH</a>',
	'01-01-2016' : '<a href="http://ajplus.net/">New Year\'s Day </a>',
	'12-25-2015' : '<span>Christmas Day</span>',
	'12-31-2015' : '<span>New Year\'s Eve</span>'
};